exports.Error_Messages = Object.freeze({
    user_id_is_invalid: 'L\'id de cet utilisateur est invalide.',
    recipe_id_is_invalid: 'L\'id de cette recette est invalide.',
    user_is_empty: 'L\'utilisateur doit être renseigné.',
    email_is_empty: 'L\'email doit être renseignée.',
    title_is_empty: 'Le titre doit être renseigné.',
    description_is_empty: 'Veuillez ajouter une description d\'au moins 10 caractères.',
    user_not_found: 'Utilisateur introuvable.',
    recipe_not_found: 'Recette introuvable.',
    email_existing: 'Email déjà existante.',
    invalid_email: 'Veuillez entrer une adresse email valide',
    title_existing: 'Titre déjà existant.',
    username_existing: 'Ce nom d\'utilisateur existe déjà.',
    user_existing: 'Utilisateur déjà existant.',
    password_is_empty: 'Le mot de passe doit contenir au moins 4 caractères.',
    password_is_needed: 'Veuillez entrer votre mot de passe.',
    invalid_credentials: 'Mauvais identifiants de connexion.',
    error_saving: 'Une erreur est survenue durant la sauvegarde.',
    incorrect_params: 'Paramètres incorrectes.',
    unauthorized_action: 'Vous n\'avez pas les permissions requises pour faire ceci.',
    password_no_match: 'Veuillez répéter le nouveau mot de passe à l\'identique.',
    invalid_password: 'Le mot de passe est incorrect.',
    invalid_old_password: 'Le mot de passe ne correspond pas à votre mot de passe actuel.',
    old_password_empty: 'Veuillez entrer votre ancien mot de passe pour le modifier.',
    new_password_empty: 'Veuillez entrer un nouveau mot de passe.',
    check_password_empty: 'Veuillez répéter votre nouveau mot de passe.',
    password_cannot_match: 'Le nouveau mot de passe doit être différent du mot de passe actuel.',
    invalid_filter: 'Filtre incorrect.',
    not_integer: 'Veuillez entrez un nombre entier.',
    already_liked: 'La recette est déjà dans vos favoris.',
    already_taged: 'La recette possède déjà ce tag.',
    tag_not_found: 'Tag introuvable.',
    tag_existing: 'Ce tag existe déjà.',
    tag_is_empty: 'Veuillez entrer un nom de tag.',
    recipe_tag_not_found: 'Ce tag n\'existe pas sur cette recette.',
    month_already_added: 'La recette possède déjà ce mois.',
    month_not_found: 'Ce mois n\'existe pas.',
    ingredient_not_found: 'Cet ingrédient n\'existe pas ou n\'appartient pas à cette recette.',
    like_not_found: 'Vous ne pouvez retirer cette recette de vos favoris car elle ne s\'y trouve pas',
    step_is_needed: 'Une étape est nécessaire pour créer une recette.',
    ingredient_is_needed: 'Un ingrédient est nécessaire pour créer une recette.',
    order_is_needed: "Veuillez donner un ordre valide."
})
